#!/bin/sh

mkdir -p multiplayer_game

cc -o multiplayer_game/multiplayer_game_server src/server.c \
   -Wall -Wextra -pedantic

cc -o multiplayer_game/multiplayer_game_client src/client.c \
   -Wall -Wextra -pedantic
