#!/bin/sh

mkdir -p multiplayer_game

# GLAD
cc -o glad.o -c lib/glad/glad.c -Ilib
ar rcs multiplayer_game/libglad.a glad.o
rm glad.o

# STBI
cc -o stbi.o -c lib/stbi/stb_image.c -Ilib
ar rcs multiplayer_game/libstbi.a stbi.o
rm stbi.o

CFLAGS_SERVER="-Wall -Wextra -pedantic -g -fsanitize=address"

cc -o multiplayer_game/server src/server.c src/cmath.c src/net.c \
   $CFLAGS_SERVER -lm

DEFINIES_CLIENT="-DCWD=\"$(pwd)\""
CFLAGS_CLIENT="-Wall -Wextra -pedantic -g -fsanitize=address -Ilib -I/usr/include/freetype2"
LDFLAGS_CLIENT="-Lmultiplayer_game -lX11 -lGL -lglad -lstbi -lfreetype -lm"
SRC_CLIENT="\
   src/client.c \
   src/renderer.c \
   src/platform/x11.c \
   src/cmath.c \
   src/net.c"

cc -o multiplayer_game/client $SRC_CLIENT \
   $CFLAGS_CLIENT $LDFLAGS_CLIENT
   
